apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - id: build
        name: Build using the shared action
        uses: calculi-corp/cb-internal-shared-actions/build@v3
        with:
          run-unit-test: "false"
          go-binary-build: "true"
          go-binary-name: ${{ env.application_name }}
          kaniko-build: "true"
          tar-path: container-image.tar
          dockerfile-path: Dockerfile-new
          registry-url: ${{ vars.staging_image_registry }}
          registry-image-name: ${{ env.application_name }}
          registry-type: ECR
          oidc-iam-role: ${{ vars.oidc_staging_iam_role }}
          trivy-scan-container: "false"
          unit-test-percent: "50"
      - name: Upload artifact using action
        if: ${{ vars.workflow_execution_env != 'production' }}
        uses: docker://020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/assets-plugin-chain-utils:latest
        with:
          entrypoint: assets-plugin-chain-utils
          args: upload-binary
        env:
          INPUT_CLOUDBEES_API_TOKEN: ${{ cloudbees.api.token }}
          INPUT_CLOUDBEES_API_URL: ${{ cloudbees.api.url }}
          INPUT_FILE_PATH: "container-image.tar"
          INPUT_FILE_TYPE: "container"
          INPUT_STEP_ID: $${{ step.id }}
          INPUT_NOTIFY_ASSET_SERVICE: "true"
          INPUT_DEBUG: "true"
